# Generated by Django 4.1.3 on 2022-11-12 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="election",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="election",
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elections.election",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="candidate",
            name="race",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elections.race",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vote",
            name="race",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elections.race",
            ),
            preserve_default=False,
        ),
    ]
