# Generated by Django 4.1.3 on 2022-11-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "elections",
            "0002_remove_candidate_election_remove_vote_election_race_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
